apiVersion: apps/v1
kind: Deployment 
metadata:
  name: geolocation
  labels:
    app: geolocation
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
          app: geolocation
    spec:
      containers:
      - name: geolocation
        image: docker.io/messershiraz/devops-frontend
        imagePullPolicy: Always
        ports: 
        - containerPort: 8501
      - name: geolocation-backend
        image: docker.io/messershiraz/devops-backend
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
      - name: geolocation-logger
        image: docker.io/messershiraz/devops-logger
        imagePullPolicy: Always
        ports: 
        - containerPort: 8000


  # kubectl apply -f deployment.yaml
