apiVersion: v1
kind: Service
metadata: 
    name: geolocation
spec:  
  selector:
    name: devops-frontend-1
  ports:
    - protocol: TCP
      port: 8502
      targetPort: 8501
  type: NodePort
# kubectl apply -f service.yaml
