apiVersion: v1
kind: Service
metadata: 
    name: logger
spec:  
  selector:
    app: geolocation-logger
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
# kubectl apply -f service.yaml
