apiVersion: v1
kind: Service
metadata: 
    name: frontend
spec:  
  selector:
    app: geolocation-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
# kubectl apply -f service.yaml
